#!/usr/bin/env python3
import argparse
import pathlib
import re


DEFINE_RE = re.compile(r"^#define\s+([A-Z0-9_]+)\s+(\d+)\s*$")


def zig_name(c_name: str) -> str:
    return c_name.lower()


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert a Maxmod soundbank header to Zig constants.")
    parser.add_argument("header", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    defines: list[tuple[str, int]] = []
    for line in args.header.read_text().splitlines():
        match = DEFINE_RE.match(line)
        if not match:
            continue
        name, value = match.groups()
        if name.startswith(("MOD_", "SFX_", "MSL_")):
            defines.append((zig_name(name), int(value)))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as out:
        out.write("// Generated by tools/soundbank_header_to_zig.py. Do not edit by hand.\n\n")
        for name, value in defines:
            out.write(f"pub const {name}: u16 = {value};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
